### ISSUE TITLE
TransacB - one frame not decoded

### ISSUE THREAD

**Issue by chrisrock1984** [josevcm/nfc-laboratory#29]
when running transacB polling, the frame before the last is not decoded but clearly visible in the signal windows.
decoding itself runs perfect, except after ATTRIB the decoder seems to be "blind" for some time.
![image](https://github.com/josevcm/nfc-laboratory/assets/22988621/5feec36c-3228-43e9-b2d5-2cb2bd8117f3)
![image](https://github.com/josevcm/nfc-laboratory/assets/22988621/39696c06-0b5d-4e00-98be-fdd63b0aab9b)

**Comment by josevcm** [comment]
Hi

Yes, I know this case, the message is not detected because I did not find the specification for that modulation, it may be a variation of type B, but it did not meet the characteristics of the documents that appears in /doc/pdf.

If you know what it is, it would help me identify it correctly.

Thanks!

**Comment by josevcm** [comment]
This issue is already fixed in New versión, please check again
